### ISSUE TITLE
Integration on SwiftUI

### ISSUE THREAD

**Issue by alexisgarciaa** [datatrans/ios-sdk#11]
thanks for this amazing sources i have been looking and option to integrate it on swiftUI but there is not info about it, it would be so amazing to see if this is possible.

**Comment by bacherma** [comment]
Hi @alexisgarciaa, I hope you could find a way to integrate it into your project. FYI: We will add convenience methods for SwiftUI in the next release (3.2). It should then work out of the box in most cases.

**Comment by bacherma** [comment]
We have released [version 3.2.0]([https://github.com/datatrans/ios-sdk/releases/tag/3.2.0) with convenience methods for SwiftUI integrations.
