### ISSUE TITLE
"CA next bank" TWINT not working

### ISSUE THREAD

**Issue by Kevinrob** [datatrans/ios-sdk#13]
Hi,

A user report us that the [Twint app from "CA next bank"](https://apps.apple.com/ch/app/ca-next-bank-twint/id6443913632?l=fr) is not found by the SDK.
I see that the app was published on may 2023 ℹ️ 

Do you have to do something on your side?

![image](https://github.com/datatrans/android-sdk/assets/4509277/f594e8e2-d0af-475c-8115-4d6092258667)

cc @AlexNsbmr

**Comment by bacherma** [comment]
Hi @Kevinrob,

1. Do you have `twint-issuer37` in your query schemes?
2. If yes, can you try to directly invoke URL twint-issuer37://something in Safari? If this does not open the app, it is an issue with the banking app.

**Comment by AlexNsbmr** [comment]
@bacherma
1. Yes we have it in the query schemes
2. I tried and it redirect to the correct Twint App (CA next bank TWINT)

**Comment by AlexNsbmr** [comment]
@bacherma any news about it ?

**Comment by bacherma** [comment]
Hi @Kevinrob, @AlexNsbmr,

We cannot reproduce this issue. Both apps are recognized by the SDK. There must be an issue with querying twint-issuer37 (CA) and twint-issuer35 (Yuh) in your app. Does your app perform other app scheme queries unrelated to payments?

![IMG_4050](https://github.com/datatrans/ios-sdk/assets/4012759/b6d0528d-01f1-48b0-941b-3fe09711a4cb)

**Comment by AlexNsbmr** [comment]
@bacherma Yes we have other queries that are unrelated to payment. We have several ones for Facebook for exemple and for twint it goes from `twint-issurer1` to `twint-issuer50`.

**Comment by bacherma** [comment]
@AlexNsbmr, Apple unfortunately restricts the total number of schemes that can be queried to 50.

This means:
- If you invoke TWINT (1-50) before querying your Facebook schemes, all your other queries will fail even if the apps are installed
- If you query your other schemes before invoking TWINT, all twint-issuerXY queries will fail for XY > (50 - #number of your scheme queries)
- There is also PostFinance and other payment methods (Swish, Vipps) further limiting the number of schemes that can be queried

We are now recommending to only use twint 1 - 40 to give merchants room for other apps, and we're looking for a solution for future Twint apps that would go above 40. This doesn't help though if you need more than 10 app schemes besides TWINT.

**Comment by AlexNsbmr** [comment]
@bacherma thank you for your clear answer, we will try to get rid of the extra Twint schemes
