### ISSUE TITLE
[Feature]: Add Privacy Manifest

### ISSUE THREAD

**Issue by LaurentChennaouiDD** [datatrans/ios-sdk#14]
Apple is requiring app developers and third party SDKs to declare their use of the Required Reason APIs via a Privacy Manifest.

Is DataTrans planning to add this to the iOS SDK? And if not, could it be added? Thanks!

[Privacy Manifest - Apple Documents](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)
[Required Reason API Documents](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

Thanks!

**Comment by bacherma** [comment]
Hi @LaurentChennaouiDD, thank you for your message.

SDK version 3.6.0 already contains the `PrivacyInfo.xcprivacy` manifest. If your app supports PayPal or Klarna, please update to version 3.6.1, which also includes updated dependencies with privacy manifests.
