### ISSUE TITLE
Failed to create 0x88 image slot (alpha=1 wide=1) (client=0xfc928308) [0x5 (os/kern) failure]

### ISSUE THREAD

**Issue by yudiz-shivam** [datatrans/ios-sdk#15]
![Screenshot 2024-04-16 at 10 14 41 AM](https://github.com/datatrans/ios-sdk/assets/36319802/8925caa0-097a-4f33-842b-e1b754d72222)

I am not able to enter my card number. 

I am testing this in the Simulator
iOS: 17
Xcode: 15
The minimum deployment target is: 13

**Comment by bacherma** [comment]
Hello @yudiz-shivam, this has something to do with your specific implementation. In order to reproduce and look into it, we need a sample project. Could you please attach a minimal project demonstrating the issue?

**Comment by yudiz-shivam** [comment]
Hello @bacherma 

        getToken { [weak self] (token) in
            self?.parent.hideCentralSpinner()
            if let tok = token {
                    let transaction = Transaction(mobileToken: tok)
                    transaction.delegate = self
                    
                    transaction.options.testing = true
                    transaction.options.useCertificatePinning = true
                    transaction.options.appCallbackScheme = "my.XXXX.datatrans"
//                
//                    // transaction.options.applePayConfig = ""
//                    transaction.options.cardLabelType = .creditOrDebitCard
                    
//                    let theme = ThemeConfiguration()
//                    theme.barBackgroundColor = UIColor.hexStringToUIColor(hexStr: "00D06A")
//                    theme.barLinkColor = UIColor.white
//                    theme.barTitleColor = UIColor.white
//                    theme.buttonColor = UIColor.hexStringToUIColor(hexStr: "00D06A")
//                    theme.buttonTextColor = UIColor.white
//                    theme.linkColor = UIColor.white
//                    
//                    transaction.theme = theme
                    transaction.start(presentingController: vc.navigationController!)
            } else {
                comp?(false)
            }
        }
        
This is a code which opens Datatrans payment SDK. 
getToken is a function used to get the mobile token to invoke SDK.

**Comment by bacherma** [comment]
Hi @yudiz-shivam, your code looks fine. Is your app based on UIKit, or are you mixing SwiftUI and UIKit? The reports we found online seem to be related to mixing the technologies. You could try invoking us from SwiftUI instead of a view controller.

In any case, since we have never heard about this from other customers and are not able to reproduce it, can you please provide us with a minimal project showing this behavior? You can just duplicate your project and remove everything unrelated. Just hard-code the token string in the project, we can then replace it with something from our backend.

**Comment by Yudiz-subhranshu** [comment]
Hello @bacherma 
I've prepared a minimal demo project that replicates the issue we've been encountering. In this version, I've removed all unrelated code and hard-coded the token string for your convenience. Please find the attached project.

[PackageDemo.zip](https://github.com/datatrans/ios-sdk/files/15008704/PackageDemo.zip)

Looking forward to your insights and assistance.

**Comment by bacherma** [comment]
Hi @Yudiz-subhranshu, thank you for the project. Can you please also post a mobile token you used to initiate the transaction (or create a new one with the same data sent to our backend)? We would like to see how your transactions are configured.

**Comment by Yudiz-subhranshu** [comment]
Hello @bacherma 
Please find the attached project which includes a mobile token
[PackageDemo.zip](https://github.com/datatrans/ios-sdk/files/15023013/PackageDemo.zip)

**Comment by bacherma** [comment]
Hi @Yudiz-subhranshu, thanks. We are able to produce a similar message now. However, we see just a log message in the console with no impact on functionality.

In the first post @yudiz-shivam wrote "I am not able to enter my card number", but we can enter the card number just fine despite this message. Do you have some sort of debug flag/configuration/breakpoint enabled to stop or crash immediately when an unexpected state is encountered?

We will continue the investigation on our side, but I think you should be able to just ignore the message?

**Comment by Yudiz-subhranshu** [comment]
Hi @bacherma 
I've recorded the screen demonstrating the problem and included the version information for your reference:
[Unable to enter card number]
https://github.com/datatrans/ios-sdk/assets/152491178/a81d89d1-a410-40c7-ab27-8a9f9048458a

* MacOS: Sonoma 14.2.1
* Xcode: 15.2
* Simulator: iPhone 15 Pro, iOS 17.2
Could we schedule a Google Meet call to demonstrate the issue in real time? Please let us know your availability, and we'll find a suitable time to discuss and address the problem together.

**Comment by Yudiz-subhranshu** [comment]
Hello @bacherma 

I have just checked, and it is working fine on physical devices but not on the simulator 
I have already provided the simulator information in the previous message

**Comment by bacherma** [comment]
Hi @Yudiz-subhranshu, @yudiz-shivam, devs would be available today between 13:00-15:00 CEST (UTC+2) or on Monday 13:30-14:30 for a quick call to look into the issue together and try out a few things. If any of these times are suitable, please send an email to support@datatrans.ch and let us know which one works best. Please include the email addresses of the persons who will attend. Thank you.

**Comment by bacherma** [comment]
Hello @yudiz-shivam, we haven't yet heard back from you. Is this still a priority for you, or might we have missed your message?

**Comment by yudiz-shivam** [comment]
@bacherma we are not facing an issue on the Physical device, we were testing on the Simulator and it is still not working, now we are testing things on the physical device. 
Thank you for your quick response.
