### ISSUE TITLE
SwiftUI Integration issue

### ISSUE THREAD

**Issue by Jean-PhilippeDESCAMPS** [datatrans/ios-sdk#17]
Hello, 

I'm currently working on integrating your SDK in a Mobile SDK Project.
I have choose to develop with SwiftUI. I'm using version 3.4.0.

Here some code to see how I have implemented it :

```
@State var showPCIProxy: Bool = false
@Binding var pcipTokenization: PCIPTokenization?

Button(action: {
                        pcipTokenization = PCIPTokenization(merchantId: merchantId, paymentMethodTypes: [.Visa, .MasterCard])
                        let tokenizationOptions = PCIPTokenizationOptions()
                        tokenizationOptions.testing = true
                        pcipTokenization?.options = tokenizationOptions
                        
                        showPCIProxy.toggle()
}, label: {
                    Text("Pay · 120,00€")
                        .foregroundColor(.white)
})
```

I have tested 2 different way to show your prompt with :

```
NavigationLink(isActive: $showPCIProxy, destination: {
                        datatrans(startWithPCIPTokenization: $pcipTokenization)
                    }, label: {
                        EmptyView()
                    })
```

or

```
.fullScreenCover(isPresented: $showPCIProxy) {
            datatrans(startWithPCIPTokenization: $pcipTokenization)
        }
```

But the result is not what I expected. Every time I push the button my view is pushed again and not your view. 
Hope you will have all you need to help me during my journey. :)

Regards, 

Jean-Philippe

**Comment by serhii-libin** [comment]
Hello @Jean-PhilippeDESCAMPS , 

Thank you for the question - here is how to make it work:

```
    var body: some View {
        Button("Pay", action: {
           startPCIPTokenization()
        })
        
        ...
        
        .datatrans(startWithPCIPTokenization: $pcipTokenization)
    }
```

From the docs:
> startWithPCIPTokenization - A binding variable to a PCIPTokenization object previously initialized and configured. When the PCIPTokenization object is set to a non-nil value the PCIPTokenization is started immediately. Make sure to fully configure the PCIPTokenization before assigning it. The SDK sets the PCIPTokenization to nil when it is finished.

Please make sure to specify `pcipTokenization.delegate` so you can handle the result

**Comment by serhii-libin** [comment]
I see the issue. Please use **State** for pcipTokenization. This should resolve the problem. Everything else in your code looks fine.
```
@State var pcipTokenization: PCIPTokenization?
```
