### ISSUE TITLE
How to Link to `DTCardScanner`

### ISSUE THREAD

**Issue by nidegen** [datatrans/ios-sdk#18]
We are looking to upgrade to the newest SDK version and noticed there was not package product for `DTCardScanner`. 

Is this a mistake or how should we link to it now?

**Comment by bacherma** [comment]
You are right, it is redundant and should be removed. But again, this won't affect your integration, there is no dependency anymore. Thanks!

**Comment by nidegen** [comment]
Bitte gärn gscheh ;)
