### ISSUE TITLE
SDK not integrable 

### ISSUE THREAD

**Issue by Avega-DanDie** [datatrans/ios-sdk#3]
Good day
I'd like to integrate the Datatrans SDK into our mobile app, but without success until now.
So far, I integrated the dependency via Xcode's Swift Package dependency. There I pointed to this repository (https://github.com/datatrans/ios-sdk) with version 1.4.0 . This step passed without any errors. But when I import Datatrans-Swift module in the app delegate, for testing purposes, the needed classes from the example code cannot be resolved (please see screenshot for details). Xcode states, that the number of passed arguments to the Transaction constructor do not match. When I try to go to the class definition, Xcode doesn't know where to go. 

Since payment is an essential part of our app, I would really appreciate any help and suggestions on this issue to be able to proceed.

Thank you very much in advance.
Best regards

Daniel

![image](https://user-images.githubusercontent.com/71312249/127130969-4e950f9e-0e63-454b-9856-e0cb076dc44f.png)

**Comment by richiehug** [comment]
Hi @Avega-DanDie ! Two ways to solve your issue:

1. Remove `paymentMethodTokens` if you won‘t use it:
> `Transaction(mobileToken: "string")`

2. Replace `[nil]` with `[]`:
> `Transaction(mobileToken: "string", paymentMethodTokens: [])`

Feel free to contact our support (support@datatrans.ch) if you run into other issues!

**Comment by Avega-DanDie** [comment]
Thanks for your answer, but sorry, that adaption didn't fix the issue. Xcode is still not able to resolve the transaction class. As stated above, Xcode says, the method doesn't require any arguments. 
I'll get in touch with you via the suggested mail address, although I already did two weeks ago regarding another issue and I didn't get an answer until today.
Thank you in advance

**Comment by richiehug** [comment]
@Avega-DanDie I‘ll make sure to take over your issue. Just add to your message that you‘d like to chat to Richie. In the meantime I‘ll check your other issues.

**Comment by richiehug** [comment]
Alright, so the main issue was, that Flutter only creates the UI screens with SwiftUI, and did not automatically add our required TransactionDelegate (which is the callback from the SDK into your code with the result). Without the TransactionDelegate the SDK will simply not work. And 'Datatrans' could not be found, because you have to use 'import Datatrans' instead of 'import Datatrans.swift'.
