### ISSUE TITLE
Previous/Old SDK version M1 support

### ISSUE THREAD

**Issue by lm2s** [datatrans/ios-sdk#5]
While trying to build the old SDK (4.6.4) on an M1(X) Mac it fails due to the static lib not having the correct arm64-sim object inside "building for iOS Simulator, but linking in object file built for iOS".

I see that it does not happen with the new version, but it'll take sometime for us to move to the new SDK version.

Is there any non-public release of the previous SDK version that supports building under M1?

**Comment by richiehug** [comment]
Hey @lm2s! Thanks for reaching out. Your question is related to the old SDK, so I'll be closing your issue here. Can you please tell us how to reach you or drop an e-mail to support@datatrans.ch so we can get back to you, once there is any update on M1 support for the old SDK?

**Comment by lm2s** [comment]
Thank you @richiehug. I've sent and email to support@datatrans.ch.
