### ISSUE TITLE
Name collision 

### ISSUE THREAD

**Issue by mrgrauel** [datatrans/ios-sdk#7]
Your repository is named `ios-sdk` which can cause a naming collision in a swift package, if any other dependencies also has the name `ios-sdk`. SPM checkouts each repo which causes the collision.

We had the issue with our sdk and renamed it, but it could easily happen with anyother.

My recommendation would be to rename your repository to `datatrans-ios-sdk` oder `datatrans-ios`.

It also helps writing `Package.swift` files, because at the moment your sdk is reference by `ios-sdk`, which makes it difficult to read and understand which sdk it is.

```swift
        .target(
            name: "SnabbleDatatrans",
            dependencies: [
                "SnabbleCore",
                "SnabbleUI",
                "ios-sdk",
            ],
            path: "Datatrans/Sources"
        )
```

**Comment by richiehug** [comment]
Hey @mrgrauel - thanks for raising this. We will check this topic next week. I‘ll keep you posted.

**Comment by richiehug** [comment]
@mrgrauel - We will rename the repo in the upcoming months, as we already planned to have a renaming anyway. We will inform you (and merchants using the SDK) once this happens.
