### ISSUE TITLE
Twint is not opening in TestFlight

### ISSUE THREAD

**Issue by azuzi** [datatrans/ios-sdk#8]
We are integrating Sdk version 1.5.1. And we can open the Twint app on Android. 
After we release the app to TestFlight in iOS, Twint app is not opening and instead gives the following error: 
``` No or outdated version of Twint is installed```. 

Even though we have a newest version installed. 

But when we debug using a real device connected to xcode opens the Twint app.

What could be the possible reason?

![WhatsApp Image 2022-11-24 at 12 16 17 PM](https://user-images.githubusercontent.com/35772758/203771216-a5b0babc-844e-4507-bcdc-32f1ccc2ff8d.jpeg)

**Comment by richiehug** [comment]
Hey @azuzi

- Please update to the latest SDK release.
- Twint can only be tested on a real device. Never on the simulator.
- Please make sure you are setting the schemes required for Twint - read more here: https://docs.datatrans.ch/docs/mobile-sdk#additional-requirements-for-ios

**Comment by azuzi** [comment]
@richiehug ,

Thanks. 
1. We will try to migrate. Do you have a migration guide line from version 1.5.x to 2.x.x ?
2. Yeah we are testing on real device connected to xcode and it's working.  But when we did the beta release to iOS TestFlight Twint app is not opening (gives the above mentioned error. Refer to the image ).
3. Yes, we have already set up the ```LSApplicationQueriesSchemes``` in the ```info.plist``` file.

**Comment by richiehug** [comment]
1. I'm afraid there's no migration guide. The best thing would be to upgrade to 2.0.0 and then one minor after the other.
2. TestFlight should not be an issue. We have several apps that run via TestFlight and can open Twint.
3. Good.
4. Check the tab `.plist RAW` in the docs. It shows you how to integrate it. We recommend appending at least 40 values.

When testing against a productive Datatrans merchantId, only real Twint applications can be used. When testing against a sandbox Datatrans merchantId, only the Twint test app (PAT) can be used. Maybe based on some setting, when testing your TestFlight build you are already on production.

**Comment by richiehug** [comment]
@azuzi any news on this?
